Include potentially missing sys/select.h
Patch by Ingo Feinerer <feinerer@logic.at>:

the compilation of E16 fails on OpenBSD with following error message:

enlightenment-1.0.20/e16-1.0.20/eesh/main.c:90:4: error: use of undeclared identifier 'fd_set'
   fd_set              fd;
   ^

enlightenment-1.0.20/e16-1.0.20/eesh/main.c:227:2: warning: implicit declaration of function 'FD_ZERO' is invalid in C99 [-Wimplicit-function-declaration]
        FD_ZERO(&fd);
        ^

This is because FD_SET lives in the sys/select.h header in OpenBSD.

This seems to be the case on newer Linux systems as well:

https://linux.die.net/man/3/fd_set

 /* According to POSIX.1-2001 */
 #include <sys/select.h>